# Generated by Django 5.0.6 on 2024-07-09 11:13

import book.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=book.helpers.SaveMedia.save_book_image_path),
        ),
    ]
